apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-api
    spec:
      containers:
        - name: springboot-api
          image: hyleung/springboot-api:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: springboot-api
  ports:
    - port: 8080
  type: NodePort
